apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-dev-label-key
  annotations:
    policies.kyverno.io/title: Require 'dev' Label
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-env-label
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - test-ns
      validate:
        message: "Deployment의 라벨에는 env가 포함되어야 하며, 값은 dev여야 합니다."
        pattern:
          metadata:
            labels:
              env: "dev"